spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      #ddl-auto: create   # DDL 재생성
      ddl-auto: none      # DDL 재생성 (X)
    properties:
      hibernate:
        show_sql: true   # sql show (System.out 을 통해 출력)
        format_sql: true # console formatting
        default_batch_fetch_size: 100 # DB > 'IN' Query 개수 설정 (최대 1000개까지 IN 허용) - # N+1 이슈 > 1+1 로 최적화

logging:
  level:
    org.hibernate.SQL: debug # Logger 를 통해 출력
    org.hibernate.type: trace # JPA 쿼리 파라미터 출력